### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by KingMichaelPark** [rose-pine/tmux#1]
the optional step in the readme is not optional, it doesn't apply unless the theme version is explicitly mentioned

**Comment by mrs4ndman** [comment]
I really did miss the default setting on the code (couldn't get it to work with a default option. Thanks for letting me know! Will change it

**Comment by mrs4ndman** [comment]
If you have any more feedback for the plugin (apart from the mistake I didn't see :) ), please do let me know

**Comment by KingMichaelPark** [comment]
Aside from that it's perfect! Thank you very much for effort!

**Comment by mrs4ndman** [comment]
When I get the time, I will extend the plugin to be more modular and make toggles / defaults for many of the options, including Rosé-Pine-like terminal colors
