### ISSUE TITLE
More controls for configuration

### ISSUE THREAD

**Issue by SamYouatt** [rose-pine/tmux#11]
Love this theme but there are a few more configurations I would like it to have:
- would be good to have an option to change the window separator (the blue triangle in this image)
- option to disable icons altogether (I personally just prefer text)
- option to change the background colour of the current window, I'm sure I can get use to looking for the yellow to signify the current one but a different background colour or similar would make it super obvious to me

<img width="475" alt="image" src="https://github.com/rose-pine/tmux/assets/31775205/19456fdf-4970-4c4f-8dfb-0edd2a80528f">

**Comment by mrs4ndman** [comment]
> Love this theme but there are a few more configurations I would like it to have:
> 
>     * would be good to have an option to change the window separator (the blue triangle in this image)
> 
>     * option to disable icons altogether (I personally just prefer text)
> 
>     * option to change the background colour of the current window, I'm sure I can get use to looking for the yellow to signify the current one but a different background colour or similar would make it super obvious to me
> 
> 
> <img alt="image" width="475" src="https://user-images.githubusercontent.com/31775205/254025774-19456fdf-4970-4c4f-8dfb-0edd2a80528f.png">

Happy that you like the theme / plugin :)
The features you are suggesting are easy to implement and useful. On it!

**Comment by mrs4ndman** [comment]
I am currently busy with life, so the current active window stuff will have to wait, as it doesn't seem to be very straightforward to create and expose for user choice :sweat_smile:. The other ones should work

**Comment by mrs4ndman** [comment]
@SamYouatt Does #19 meet the feature need you mentioned? If so, great!

**Comment by mrs4ndman** [comment]
I think this set of features is done, so closing for now :)
Be sure to comment if you think they aren't :wink:
