### ISSUE TITLE
Unintuitive window title behavior

### ISSUE THREAD

**Issue by fuadsaud** [rose-pine/tmux#12]
Hi! Thanks for all the work, it's super nice to have the tmux colorscheme match the rest of my setup.

I find it a bit unintuitive to have the current working directory of the last selected pane in the as the window label in the window list and have the actual window title only show for the one window currently selected.

Wouldn't that be a bit better the other way around? That way the window list would clearly describe all the windows that exist and the cwd would only show up for the currently selected window/pane.

**Comment by mrs4ndman** [comment]
Hey there. Happy you like it!

Can you give me some context about your setup?
- What are your settings for the plugin?
- Have you updated the plugin (if installed through TPM) or git pull'ed the repository on the installation directory? (TPM update keybind is generally Prefix + U)

I could add a setting that makes the current active window display the active pane's CWD

**Comment by fuadsaud** [comment]
>What are your settings for the plugin?
I'm using the default settings

>Have you updated the plugin (if installed through TPM) or git pull'ed the repository on the installation directory? (TPM update keybind is generally Prefix + U)
Yes! Latest version.

---

To illustrate my point, consider the following hypothetical setup:

* A directory structure that looks like this:

```sh
~/rose-pine-example ❯❯❯ tree -a
.
├── project-1
│   └── subfolder
├── project-2
│   └── subfolder
└── project-3
    └── subfolder

7 directories, 0 files
```

* 3 tmux windows setup as follows:

|           | window title |         cwd         |
|-----------|--------------|:-------------------:|
| window #1 | project 1    | project-1/subfolder |
| window #2 | project 2    | project-2/subfolder |
| window #3 | project 3    | project-3/subfolder |

What I get today is the following (assuming I'm standing in window #1):

<img width="795" alt="Screenshot 2023-07-20 at 10 45 34" src="https://github.com/rose-pine/tmux/assets/1993787/8aea8acd-c202-44ed-94bd-bcab5520ecba">

* the window title is only shown for the currently selected window
* the CWD of the most recently selected pane in each window is shown for all windows

To me that's a bit confusing:

* when looking at the window list, I want to be able to, at a glance, know what I need to press to get there. Because the window list doesn't show the window title, but rather the CWD of the currently selected pane in that window, that is not possible.
* I don't see value in seeing the CWD of a pane in a window that isn't selected

My suggestion would be to offer an experience that is the other way around:

* the CWD of the current pane of the currently selected window is shown on the left (where the window title is right now), since that is probably the only CWD that's relevant to know at all times
* the window title is shown for each window in the windows list (perhaps defaulting to the CWD or running program of the currently selected pane, if no window title is set).

Perhaps this could be done as a pair of settings: what to show in the left side indicator and what to show as the label for each window in the window list.

**Comment by mrs4ndman** [comment]
![image](https://github.com/rose-pine/tmux/assets/121260905/97fb928a-2b4f-41b2-b41a-f3520d6920d1)
Just tested this, and even with the CWD option for the windows set to "on", it does not show the directory.
I am aware that you cannot set custom window names when the "directory-as-window-name" option is set. Will look into it during the summer.

**Comment by fuadsaud** [comment]
I just updated the plugin and it seems that the default behavior now is the one I described. Thanks for making that possible.
