### ISSUE TITLE
Disable windows re-org

### ISSUE THREAD

**Issue by yosiat** [rose-pine/tmux#13]
Hi!

Thanks for this awesome plugin and theme! I recently moved to Rose Pine for my default theme. but I would like to change the how windows are shown in the current plugin.

With my default tmux config this what I get:
<img width="1104" alt="Screenshot 2023-07-27 at 14 11 32" src="https://github.com/rose-pine/tmux/assets/306253/a6c98dcf-cf25-4f9d-ac28-28e5fa5e0ea3">

List of window, the selected one have `*` before it.

But with rose-pine tmux, the list is dynamic and changes according to current focused window.
<img width="1104" alt="Screenshot 2023-07-27 at 14 14 49" src="https://github.com/rose-pine/tmux/assets/306253/a6f57daa-044f-412d-8d5a-0618c187c25c">

I find this really confusing and I would like this list to be static except the change of selected one.

Is it possible to configure this option and disable it?

**Comment by mrs4ndman** [comment]
Can you explain in what way are they getting "reorganised"? The only thing the plugin should do is highlight differently the current one. 

EDIT: As for the option, it would mean rebuilding the window-displaying code and adding the toggle would be the least troublesome part

**Comment by yosiat** [comment]
@mrs4ndman I will elaborate:
In my plain tmux config, when I select a window it just showed as `2:another-win*` (as you can see in the first screenshot) and then to go to "yosi" named window, it's still the first-window.

With rose-pine, we are in the same state, two windows are opened, and I am "another-window", but:
1. another-window moved to the left
2. and "yosi" moved to right

> As for the option, it would mean rebuilding the window-displaying code and adding the toggle would be the least troublesome part

If this is troublesome, I can do this change in my own fork if you can instruct me on how to achieve this.

**Comment by mrs4ndman** [comment]
When using this config for the plugin: 
```sh
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'
```
Does it keep happening? I am testing trying to recreate the undesired window movement (I don't know what is causing it at the moment)

EDIT: I need to figure out how to make the plugin show the custom window name when set by the user

**Comment by mrs4ndman** [comment]
Thanks to this issue, I have re-thought the plugin's options, so the next commit(s) will implement the options to change the default behaviour. Without setting anything, the windows will behave the same as if there was no plugin.

![image](https://github.com/rose-pine/tmux/assets/121260905/5bfdee11-a475-4917-b174-3e9db30f20fd)

Does this look cool as default behavior?

**Comment by mrs4ndman** [comment]
This afternoon I will probably update the README, and it has a high probability of implementing breaking changes, so I might create an issue for those to track them.

EDIT: Changes already commited (readme updated) and a "Breaking changes" issue has been opened for future occurrences.
What is the configuration for the plugin on your `.tmux.conf`? I suppose the default one

**Comment by mrs4ndman** [comment]
@yosiat Having these options inside the config leads to the default tmux behaviour of active & non-active windows:
```tmux
set -g @rose_pine_variant 'main'
set -g @rose_pine_show_current_program 'off'
```
![image](https://github.com/rose-pine/tmux/assets/121260905/1b51f45b-efff-42de-a708-21b7db52d4dc)

I haven't had problems with renaming windows, although it might be a bug / oversight on my side.

**Comment by mrs4ndman** [comment]
Closing because the original issue has subsided :smiley:
