### ISSUE TITLE
missing a section about how to install and source it 

### ISSUE THREAD

**Issue by mikemols** [rose-pine/tmux#15]
Missing a  section or paragraph in the readme about having to do this:

<prefix + I> to fetch and source the plugin. 

Like, I was spending a bit too long on figuring this out as a tmux newbie, so if the documenation actually had this in, I would have spared a lot of time debugging. I think this will help other newbies as well.

**Comment by mrs4ndman** [comment]
Thanks for the tip, are the new changes good?
