### ISSUE TITLE
A way to not show visual alerts when the content of a window updates

### ISSUE THREAD

**Issue by arunavdey** [rose-pine/tmux#16]
Loving the look of this.

On the status bar where the windows are shown, is it possible to disable all visual alerts that happen in each different window?

**Comment by mrs4ndman** [comment]
It is true that inside the plugin's code it is set to "on". https://github.com/rose-pine/tmux/commit/08eb9a29eac551bc07b12a3df87c5c122190ca82 has been put right now to fix it. From what I have seen online, it highlights each "active" window based on the changes in text inside it, so it might be that you have many "active" windows per se. 
If you want to enable it by yourself:
```bash
set -g monitor-activity on
```
Or you could look at the [monitor-silence setting](https://github.com/tmux/tmux/wiki/Advanced-Use#alerts-and-monitoring), also inside `man tmux`

Thanks for the tip!
