### ISSUE TITLE
Problem with left separator in pane tabs

### ISSUE THREAD

**Issue by masolnada** [rose-pine/tmux#25]
Hello ,

I'm running the following config in NixOS on tmux 3.4.

```
{
    plugin = rose-pine;
    extraConfig = ''
      set -g @rose_pine_variant 'main'
      set -g @rose_pine_host 'off'
      set -g @rose_pine_date_time "%H:%M"
      set -g @rose_pine_user 'off'
      set -g @rose_pine_directory 'off'
      set -g @rose_pine_default_window_behavior 'off'
      set -g @rose_pine_disable_active_window_menu 'on'
      set -g @rose_pine_show_current_program 'off'
      set -g @rose_pine_bar_bg_disable 'off'
      set -g @rose_pine_current_window_icon '󰣘'
      set -g @rose_pine_date_time_icon '󱑍'
      set -g @rose_pine_hostname_icon '󰒋'
      set -g @rose_pine_window_status_separator "  "
      set -g @rose_pine_left_separator '  '
      set -g @rose_pine_right_separator '  '
      set -g @rose_pine_field_separator '  '
    '';
  }
```

I would expect to see  the left separator in my status bar:

![image](https://github.com/rose-pine/tmux/assets/2914776/8a8dc73b-ad49-49fd-9f09-021d3d5d3799)

But I'm getting:

![image](https://github.com/rose-pine/tmux/assets/2914776/d6207ed3-af0a-4cea-803a-f948508829dc)

Do I have something wrong in the config or is it a bug?

Thanks!

**Comment by mrs4ndman** [comment]
Hi there!
Have you tried changing the value from this to on? ↓
```tmux
set -g @rose_pine_show_current_program 'off'
```

**Comment by masolnada** [comment]
That did the trick! Thanks!

**Comment by masolnada** [comment]
Shouldn't the rendering of the icon be independent of whether the current program detection is enabled?

**Comment by mrs4ndman** [comment]
The thing is that these 2 options fiddle around with the icons.
```tmux
set -g @rose_pine_default_window_behavior 'on' # Forces tmux default window list behaviour
set -g @rose_pine_show_current_program 'on' # Forces tmux to show the current running program as window name
```
Could make an option just to change the little `:` into an arrow / user-defined symbol :thinking:

**Comment by masolnada** [comment]
> The thing is that these 2 options fiddle around with the icons.
> 
> ```shell
> set -g @rose_pine_default_window_behavior 'on' # Forces tmux default window list behaviour
> set -g @rose_pine_show_current_program 'on' # Forces tmux to show the current running program as window name
> ```
> 
> Could make an option just to change the little `:` into an arrow / user-defined symbol 🤔

That would be nice! If you need me to test the change, let me know.

**Comment by mrs4ndman** [comment]
> That would be nice! If you need me to test the change, let me know.

![image](https://github.com/rose-pine/tmux/assets/121260905/f23261d1-6a2c-484c-9619-25b07a3e1d8f)
Does this look kinda like what you were looking for?
