### ISSUE TITLE
return of 1 on sourcing

### ISSUE THREAD

**Issue by ordotools** [rose-pine/tmux#27]
Installing the plugin with tpm returns `1` after sourcing. I had previously had the catppuccin theme installed without an issue. These are the only two lines that I added to my really small config file, located at `~/.config/tmux/tmux.conf`:
```bash
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'
```

**Comment by mrs4ndman** [comment]
Have you cleaned up the `~/.tmux/plugins/tmux` directory?

Both catppuccin and this theme use the "tmux" namespace for the tmux plugin files

**Comment by ordotools** [comment]
Thank you. I ended up re-cloning tpm and that cleaned up the issue.
