### ISSUE TITLE
Can't install from tpm.

### ISSUE THREAD

**Issue by kouovo** [rose-pine/tmux#28]
```
set -g @tpm_plugins '           \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tmux-yank       \
   christoomey/vim-tmux-navigator \
   jimeh/tmuxifier              \
   rose-pine/tmux               \
'
# set -g @plugin 'rose-pine/tmux'
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'jimeh/tmuxifier'

set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'

```

<img width="468" alt="image" src="https://github.com/rose-pine/tmux/assets/38428853/a0aa8521-2d84-48ed-baed-5fc768ab89a8">

**Comment by kouovo** [comment]
OK, I found the solution .

I installed another theme before, `.tmux/plugins/tmux` folder name is same as `rose-pine/tmux` folder name, So i must delete the folder then press `prefix + I` to install.

**Comment by hesperaux** [comment]
I realize this issue is closed, but I just resolved the same issue tonight and what I did was fork this repo and rename it so that when tpm checks out the plugin, it will have a different folder name and the names no longer conflict. I'm guessing OP had the catppuccin theme installed (that's what was breaking mine).

**Comment by Swivelgames** [comment]
Yeah... there seems to be a trend of naming these repos `tmux`, which is probably a bad practice. I'm going to have to fork the repo and rename it as well...

**Comment by DjTuner13** [comment]
Thank you! This was very easy once done. I named it rose-pine-tmux as just 'tmux' would have been very confusing incase anyone else needs an idea.

**Comment by Swivelgames** [comment]
Indeed! Mine is [tmux-rose-pine](https://github.com/Swivelgames/tmux-rose-pine/tree/main), and I try and keep it up to date with latest as much as possible (even though this doesn't need a lot of updates.)

**Comment by Swivelgames** [comment]
It would be great if @emanonzzz reopened this, since the processes we've described are really just workarounds, and not a true fix to the problem 👍
