### ISSUE TITLE
Disable nerd font option

### ISSUE THREAD

**Issue by vivitsu** [rose-pine/tmux#30]
Is there anyway to disable the nerd font icons when using rose-pine theme for tmux? I don't really care for the icons I just want the colors.

**Comment by mrs4ndman** [comment]
[Usage → Section 5](https://github.com/rose-pine/tmux?tab=readme-ov-file#usage), you can change all the defaults for normal ASCII characters :wink:

**Comment by vivitsu** [comment]
Awesome, thank you! That fixed my problem.
