### ISSUE TITLE
Undefined variables are used: `thm_fg`, `thm_bg`

### ISSUE THREAD

**Issue by cascassette** [rose-pine/tmux#9]
See for example [here](https://github.com/rose-pine/tmux/blob/main/rose-pine.tmux#L170C14-L170C42).

I think we can just use `$thm_text` and `$thm_base` instead?

**Comment by mrs4ndman** [comment]
Appreciate the feedback, and it has been changed. This is my first open-source proyect / development, so sorry if I mess up / don't know what to do. Thanks for pointing out my mistakes :)

**Comment by cascassette** [comment]
Nice! Thank you. It was fun honestly trying to find out why it works or doesn't work. Glad to help out.
